# Generated by Django 2.0.3 on 2020-02-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=200)),
                ('ecobuy_rate', models.FloatField(verbose_name='rate')),
                ('number_of_products', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ecobuy_rate', models.FloatField(verbose_name='rate')),
                ('country', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecobuyBE.EcoUser')),
            ],
        ),
    ]
